name: Update
on: 
  workflow_dispatch:
  schedule:
    - cron:  '0 12,0 * * *'
jobs:
  UpdateUsername:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Project
      uses: actions/checkout@v2.3.4
    - name: Use Node.js 16
      uses: actions/setup-node@v2.4.1
      with:
        node-version: 16
        cache: 'npm'
    - name: Install Deps
      run: npm install
    - name: Update Username
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        GITHUB: ${{ secrets.GITHUB }}
      run: npm run start
